// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NektoTranslate.Common.Data;

#nullable disable

namespace NektoTranslate.Common.Data.Migrations
{
    [DbContext(typeof(NektoDbContext))]
    [Migration("20260905115227_SourceListings")]
    partial class SourceListings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("NektoTranslate.Chapters.Entities.Chapter", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("createdAt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("glossaryState")
                        .HasColumnType("INTEGER");

                    b.Property<int>("index")
                        .HasColumnType("INTEGER")
                        .HasColumnName("chapter_index");

                    b.Property<long>("novelId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("sourceMarkdown")
                        .HasColumnType("TEXT");

                    b.Property<string>("sourcePlainText")
                        .HasColumnType("TEXT");

                    b.Property<string>("sourceUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("translationState")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.HasIndex("novelId", "index")
                        .IsUnique();

                    b.HasIndex("novelId", "translationState");

                    b.ToTable("chapters");
                });

            modelBuilder.Entity("NektoTranslate.Chat.Entities.ChatMessage", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("costUsd")
                        .HasColumnType("REAL");

                    b.Property<long>("createdAt")
                        .HasColumnType("INTEGER");

                    b.Property<long>("novelId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("role")
                        .HasColumnType("INTEGER");

                    b.Property<string>("text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.HasIndex("novelId", "id");

                    b.ToTable("chat_messages");
                });

            modelBuilder.Entity("NektoTranslate.Glossary.Entities.GlossaryEntry", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.PrimitiveCollection<string>("aliases")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("category")
                        .HasColumnType("INTEGER");

                    b.Property<double>("confidence")
                        .HasColumnType("REAL");

                    b.Property<long?>("firstSeenChapterId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("language")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<bool>("needsReview")
                        .HasColumnType("INTEGER");

                    b.Property<string>("notes")
                        .HasColumnType("TEXT");

                    b.Property<long>("novelId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("origin")
                        .HasColumnType("INTEGER");

                    b.Property<string>("sourceTerm")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("targetTerm")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<long>("updatedAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.HasIndex("novelId", "language", "sourceTerm")
                        .IsUnique();

                    b.ToTable("glossary_entries");
                });

            modelBuilder.Entity("NektoTranslate.Jobs.Entities.ImportJob", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("createMissingChapters")
                        .HasColumnType("INTEGER");

                    b.Property<long>("createdAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("currentTitle")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("error")
                        .HasColumnType("TEXT");

                    b.Property<long?>("finishedAt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("kind")
                        .HasColumnType("INTEGER");

                    b.Property<string>("language")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<long>("novelId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("processedCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("startAtChapterIndex")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("startedAt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("state")
                        .HasColumnType("INTEGER");

                    b.Property<int>("totalCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.HasIndex("novelId", "state");

                    b.ToTable("import_jobs");
                });

            modelBuilder.Entity("NektoTranslate.Jobs.Entities.ImportJobItem", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("chapterId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("chapterIndex")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("finishedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long>("jobId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("position")
                        .HasColumnType("INTEGER");

                    b.Property<string>("sourceUrl")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<int>("state")
                        .HasColumnType("INTEGER");

                    b.Property<string>("statusArgsJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("statusCode")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("statusText")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.HasIndex("jobId", "position")
                        .IsUnique();

                    b.ToTable("import_job_items");
                });

            modelBuilder.Entity("NektoTranslate.Jobs.Entities.TranslationJob", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double?>("budgetUsd")
                        .HasColumnType("REAL");

                    b.PrimitiveCollection<string>("chapterIds")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("costUsd")
                        .HasColumnType("REAL");

                    b.Property<long>("createdAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("error")
                        .HasColumnType("TEXT");

                    b.Property<long?>("finishedAt")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("force")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("fromIndex")
                        .HasColumnType("INTEGER");

                    b.Property<int>("mode")
                        .HasColumnType("INTEGER");

                    b.Property<long>("novelId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("processedCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("scopeKind")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("startedAt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("state")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("toIndex")
                        .HasColumnType("INTEGER");

                    b.Property<int>("totalCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.HasIndex("novelId", "state");

                    b.ToTable("translation_jobs");
                });

            modelBuilder.Entity("NektoTranslate.Novels.Entities.Novel", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("createdAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("model")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<bool>("normalizeQuotes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("sourceLanguage")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("sourceUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("styleGuide")
                        .HasColumnType("TEXT");

                    b.Property<string>("targetLanguage")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("novels");
                });

            modelBuilder.Entity("NektoTranslate.Parsing.Entities.ParserScript", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("bundledOverride")
                        .HasColumnType("INTEGER");

                    b.Property<string>("displayName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<bool>("enabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("hostName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("scriptSource")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("updatedAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.HasIndex("hostName")
                        .IsUnique();

                    b.ToTable("parser_scripts");
                });

            modelBuilder.Entity("NektoTranslate.Parsing.Entities.SourceListing", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("entriesJson")
                        .HasColumnType("TEXT");

                    b.Property<int>("entryCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("kind")
                        .HasColumnType("INTEGER");

                    b.Property<long>("novelId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("readAt")
                        .HasColumnType("INTEGER");

                    b.Property<long>("startedAt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("state")
                        .HasColumnType("INTEGER");

                    b.Property<string>("statusArgsJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("statusCode")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("statusText")
                        .HasColumnType("TEXT");

                    b.Property<string>("url")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.HasIndex("novelId", "kind")
                        .IsUnique();

                    b.ToTable("source_listings");
                });

            modelBuilder.Entity("NektoTranslate.Settings.Entities.ApplicationSettings", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("chatMaxRounds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("defaultModel")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<double>("expansionFactor")
                        .HasColumnType("REAL");

                    b.Property<string>("globalStyleGuide")
                        .HasColumnType("TEXT");

                    b.Property<string>("glossaryModel")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("localModelApiKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("localModelEndpoint")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("localModelName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("maxOutputTokens")
                        .HasColumnType("INTEGER");

                    b.Property<int>("pageLoadTimeoutMs")
                        .HasColumnType("INTEGER");

                    b.Property<long>("updatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("voiceWindowChapters")
                        .HasColumnType("INTEGER");

                    b.Property<int>("voiceWindowParagraphs")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.ToTable("application_settings");
                });

            modelBuilder.Entity("NektoTranslate.Translation.Entities.ChapterChunk", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("chapterId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("costUsd")
                        .HasColumnType("REAL");

                    b.Property<long>("createdAt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("index")
                        .HasColumnType("INTEGER");

                    b.Property<string>("language")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("model")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("sourceHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("translatedText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.HasIndex("chapterId", "language", "sourceHash")
                        .IsUnique();

                    b.ToTable("chapter_chunks");
                });

            modelBuilder.Entity("NektoTranslate.Translation.Entities.ChapterTranslation", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("chapterId")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("costUsd")
                        .HasColumnType("REAL");

                    b.Property<long>("createdAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("language")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("markdown")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("model")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("origin")
                        .HasColumnType("INTEGER");

                    b.Property<string>("plainText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.HasIndex("chapterId", "language");

                    b.ToTable("chapter_translations");
                });

            modelBuilder.Entity("NektoTranslate.Translation.Entities.ChapterTranslationIssue", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("argsJson")
                        .HasColumnType("TEXT");

                    b.Property<int?>("blockIndex")
                        .HasColumnType("INTEGER");

                    b.Property<long>("chapterId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("check")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<long?>("closedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<long>("createdAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("language")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("message")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<int>("state")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.HasIndex("state");

                    b.HasIndex("chapterId", "language");

                    b.ToTable("chapter_translation_issues");
                });

            modelBuilder.Entity("NektoTranslate.Translation.Entities.TranslationTerm", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("category")
                        .HasColumnType("INTEGER");

                    b.Property<long>("createdAt")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("firstSeenChapterId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("language")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("notes")
                        .HasColumnType("TEXT");

                    b.Property<long>("novelId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("occurrences")
                        .HasColumnType("INTEGER");

                    b.Property<string>("term")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("variantsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.HasIndex("novelId", "language", "term")
                        .IsUnique();

                    b.ToTable("translation_terms");
                });

            modelBuilder.Entity("NektoTranslate.Translation.Entities.VoiceProfile", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double?>("costUsd")
                        .HasColumnType("REAL");

                    b.Property<long>("createdAt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("fromChapterIndex")
                        .HasColumnType("INTEGER");

                    b.Property<string>("language")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("model")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<long>("novelId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("summary")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("toChapterIndex")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.HasIndex("novelId", "language");

                    b.ToTable("voice_profiles");
                });

            modelBuilder.Entity("NektoTranslate.Chapters.Entities.Chapter", b =>
                {
                    b.HasOne("NektoTranslate.Novels.Entities.Novel", "novel")
                        .WithMany("chapters")
                        .HasForeignKey("novelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("novel");
                });

            modelBuilder.Entity("NektoTranslate.Chat.Entities.ChatMessage", b =>
                {
                    b.HasOne("NektoTranslate.Novels.Entities.Novel", "novel")
                        .WithMany()
                        .HasForeignKey("novelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("novel");
                });

            modelBuilder.Entity("NektoTranslate.Glossary.Entities.GlossaryEntry", b =>
                {
                    b.HasOne("NektoTranslate.Novels.Entities.Novel", "novel")
                        .WithMany("glossary")
                        .HasForeignKey("novelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("novel");
                });

            modelBuilder.Entity("NektoTranslate.Jobs.Entities.ImportJob", b =>
                {
                    b.HasOne("NektoTranslate.Novels.Entities.Novel", "novel")
                        .WithMany()
                        .HasForeignKey("novelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("novel");
                });

            modelBuilder.Entity("NektoTranslate.Jobs.Entities.ImportJobItem", b =>
                {
                    b.HasOne("NektoTranslate.Jobs.Entities.ImportJob", "job")
                        .WithMany("items")
                        .HasForeignKey("jobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("job");
                });

            modelBuilder.Entity("NektoTranslate.Jobs.Entities.TranslationJob", b =>
                {
                    b.HasOne("NektoTranslate.Novels.Entities.Novel", "novel")
                        .WithMany()
                        .HasForeignKey("novelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("novel");
                });

            modelBuilder.Entity("NektoTranslate.Parsing.Entities.SourceListing", b =>
                {
                    b.HasOne("NektoTranslate.Novels.Entities.Novel", "novel")
                        .WithMany()
                        .HasForeignKey("novelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("novel");
                });

            modelBuilder.Entity("NektoTranslate.Translation.Entities.ChapterChunk", b =>
                {
                    b.HasOne("NektoTranslate.Chapters.Entities.Chapter", "chapter")
                        .WithMany()
                        .HasForeignKey("chapterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("chapter");
                });

            modelBuilder.Entity("NektoTranslate.Translation.Entities.ChapterTranslation", b =>
                {
                    b.HasOne("NektoTranslate.Chapters.Entities.Chapter", "chapter")
                        .WithMany("translations")
                        .HasForeignKey("chapterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("chapter");
                });

            modelBuilder.Entity("NektoTranslate.Translation.Entities.ChapterTranslationIssue", b =>
                {
                    b.HasOne("NektoTranslate.Chapters.Entities.Chapter", "chapter")
                        .WithMany()
                        .HasForeignKey("chapterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("chapter");
                });

            modelBuilder.Entity("NektoTranslate.Translation.Entities.TranslationTerm", b =>
                {
                    b.HasOne("NektoTranslate.Novels.Entities.Novel", "novel")
                        .WithMany()
                        .HasForeignKey("novelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("novel");
                });

            modelBuilder.Entity("NektoTranslate.Translation.Entities.VoiceProfile", b =>
                {
                    b.HasOne("NektoTranslate.Novels.Entities.Novel", "novel")
                        .WithMany()
                        .HasForeignKey("novelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("novel");
                });

            modelBuilder.Entity("NektoTranslate.Chapters.Entities.Chapter", b =>
                {
                    b.Navigation("translations");
                });

            modelBuilder.Entity("NektoTranslate.Jobs.Entities.ImportJob", b =>
                {
                    b.Navigation("items");
                });

            modelBuilder.Entity("NektoTranslate.Novels.Entities.Novel", b =>
                {
                    b.Navigation("chapters");

                    b.Navigation("glossary");
                });
#pragma warning restore 612, 618
        }
    }
}
