// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NektoTranslate.Common.Data;

#nullable disable

namespace NektoTranslate.Common.Data.Migrations
{
    [DbContext(typeof(NektoDbContext))]
    [Migration("20260902145402_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("NektoTranslate.Chapters.Entities.Chapter", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("createdAt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("glossaryState")
                        .HasColumnType("INTEGER");

                    b.Property<int>("index")
                        .HasColumnType("INTEGER")
                        .HasColumnName("chapter_index");

                    b.Property<long>("novelId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("sourceMarkdown")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("sourcePlainText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("sourceUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("translationState")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.HasIndex("novelId", "index")
                        .IsUnique();

                    b.HasIndex("novelId", "translationState");

                    b.ToTable("chapters");
                });

            modelBuilder.Entity("NektoTranslate.Glossary.Entities.GlossaryEntry", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.PrimitiveCollection<string>("aliases")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("category")
                        .HasColumnType("INTEGER");

                    b.Property<double>("confidence")
                        .HasColumnType("REAL");

                    b.Property<long?>("firstSeenChapterId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("language")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<bool>("needsReview")
                        .HasColumnType("INTEGER");

                    b.Property<string>("notes")
                        .HasColumnType("TEXT");

                    b.Property<long>("novelId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("origin")
                        .HasColumnType("INTEGER");

                    b.Property<string>("sourceTerm")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("targetTerm")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<long>("updatedAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.HasIndex("novelId", "language", "sourceTerm")
                        .IsUnique();

                    b.ToTable("glossary_entries");
                });

            modelBuilder.Entity("NektoTranslate.Jobs.Entities.TranslationJob", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double?>("budgetUsd")
                        .HasColumnType("REAL");

                    b.PrimitiveCollection<string>("chapterIds")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("costUsd")
                        .HasColumnType("REAL");

                    b.Property<long>("createdAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("error")
                        .HasColumnType("TEXT");

                    b.Property<long?>("finishedAt")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("fromIndex")
                        .HasColumnType("INTEGER");

                    b.Property<long>("novelId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("processedCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("scopeKind")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("startedAt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("state")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("toIndex")
                        .HasColumnType("INTEGER");

                    b.Property<int>("totalCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.HasIndex("novelId", "state");

                    b.ToTable("translation_jobs");
                });

            modelBuilder.Entity("NektoTranslate.Novels.Entities.Novel", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("createdAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("model")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<bool>("normalizeQuotes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("sourceLanguage")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("sourceUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("styleGuide")
                        .HasColumnType("TEXT");

                    b.Property<string>("targetLanguage")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("novels");
                });

            modelBuilder.Entity("NektoTranslate.Translation.Entities.ChapterTranslation", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("chapterId")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("costUsd")
                        .HasColumnType("REAL");

                    b.Property<long>("createdAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("language")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("markdown")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("model")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("origin")
                        .HasColumnType("INTEGER");

                    b.Property<string>("plainText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.HasIndex("chapterId", "language");

                    b.ToTable("chapter_translations");
                });

            modelBuilder.Entity("NektoTranslate.Chapters.Entities.Chapter", b =>
                {
                    b.HasOne("NektoTranslate.Novels.Entities.Novel", "novel")
                        .WithMany("chapters")
                        .HasForeignKey("novelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("novel");
                });

            modelBuilder.Entity("NektoTranslate.Glossary.Entities.GlossaryEntry", b =>
                {
                    b.HasOne("NektoTranslate.Novels.Entities.Novel", "novel")
                        .WithMany("glossary")
                        .HasForeignKey("novelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("novel");
                });

            modelBuilder.Entity("NektoTranslate.Jobs.Entities.TranslationJob", b =>
                {
                    b.HasOne("NektoTranslate.Novels.Entities.Novel", "novel")
                        .WithMany()
                        .HasForeignKey("novelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("novel");
                });

            modelBuilder.Entity("NektoTranslate.Translation.Entities.ChapterTranslation", b =>
                {
                    b.HasOne("NektoTranslate.Chapters.Entities.Chapter", "chapter")
                        .WithMany("translations")
                        .HasForeignKey("chapterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("chapter");
                });

            modelBuilder.Entity("NektoTranslate.Chapters.Entities.Chapter", b =>
                {
                    b.Navigation("translations");
                });

            modelBuilder.Entity("NektoTranslate.Novels.Entities.Novel", b =>
                {
                    b.Navigation("chapters");

                    b.Navigation("glossary");
                });
#pragma warning restore 612, 618
        }
    }
}
